import type { DataEntity } from "@/types";

export const dummyData: DataEntity[] = [
  {
    status: "Settled",
    results: [
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1PY9ASdWe",
        memo: "MAgenta",
        height: 92899,
        timestamp: 9374188241,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1WEQ23EER",
        memo: "no Magenta",
        height: 92903,
        timestamp: 9374188277,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1WE09gfDh",
        memo: "no Magenta",
        height: 92916,
        timestamp: 9374188295,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1WEQW45iu",
        memo: "MagentA",
        height: 92922,
        timestamp: 9374188305,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVQ678fwqkwqDhGH8S8jutcmPgC1PY9ASdWe",
        memo: "MAgeNta",
        height: 93123,
        timestamp: 9374188612,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPrtyuEQ23EER",
        memo: "No Magenta",
        height: 93153,
        timestamp: 9374188662,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3DszRTyu9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1WERT67ui",
        memo: "No magenta",
        height: 93162,
        timestamp: 9374188690,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHtyVViU23wqkwqDhGH8S8jutcmPgC1WE09gfDh",
        memo: "NO MAGENTA",
        height: 93171,
        timestamp: 9374188880,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqasqDhGH8S8jutcmPDf1WESDF89o",
        memo: "no magenta",
        height: 93182,
        timestamp: 9374188901,
        block_status: "Canonical",
        signal_status: "Settled",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqASDH8S8jutcmPgC1WEQW45iu",
        memo: "MAGENTA",
        height: 93198,
        timestamp: 9374189002,
        block_status: "Canonical",
        signal_status: "Settled",
      },
    ],
  },
  {
    status: "Unsettled",
    results: [
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pt5YHg4f",
        memo: "MagEnta",
        height: 92899,
        timestamp: 9374188242,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbn0asKJ",
        memo: "No magenta",
        height: 92902,
        timestamp: 9374188255,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pb2nUIpo",
        memo: "NO Magenta",
        height: 92903,
        timestamp: 9374188278,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pb2wViAa",
        memo: "no magenta",
        height: 92909,
        timestamp: 9374188290,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1PbZ9hSrA",
        memo: "no Magenta",
        height: 92916,
        timestamp: 9374188296,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbn6YTgh",
        memo: "no magenta",
        height: 92920,
        timestamp: 9374188300,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbn4ERvb",
        memo: "MAGENTA",
        height: 92922,
        timestamp: 9374188306,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbnsd5Cv",
        memo: "MAgenta",
        height: 93101,
        timestamp: 9374188573,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbn09gHj",
        memo: "MagEnta",
        height: 93111,
        timestamp: 9374188601,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jubn8XCVztsmXgC1P",
        memo: "MAgeNTA",
        height: 93123,
        timestamp: 9374188611,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1XCVzPbn8",
        memo: "No magenta",
        height: 93133,
        timestamp: 9374188631,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1PbXc56vB",
        memo: "No MAgenta",
        height: 93153,
        timestamp: 9374188660,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbod4bNm",
        memo: "No magenta",
        height: 93162,
        timestamp: 9374188689,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbn21eRt",
        memo: "NO mAGENTA",
        height: 93171,
        timestamp: 9374188877,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbnp3Fmq",
        memo: "magenta",
        height: 93198,
        timestamp: 9374189001,
        block_status: "Pending",
        signal_status: "Unsettled",
      },
    ],
  },
  {
    status: "Invalid",
    results: [
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1PY5sUEoL",
        memo: "Magenta_magenta",
        height: 92891,
        timestamp: 9374188212,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1PY7TYuiO",
        memo: "!MAgenta",
        height: 92897,
        timestamp: 9374188232,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1PY1sCv5B",
        memo: "No_magenta",
        height: 92902,
        timestamp: 9374188254,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1WEQ4FBgh",
        memo: "n0Magenta",
        height: 92903,
        timestamp: 9374188263,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1WERT67ui",
        memo: "no-_magenta",
        height: 92909,
        timestamp: 9374188289,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGH8S8jutcmPgC1WESDF89o",
        memo: "no-magenta!",
        height: 92920,
        timestamp: 9374188299,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkwqDhGR6y7jutcmPgC1PY6hq8Mn",
        memo: "MAgenta_magenta",
        height: 93101,
        timestamp: 9374188574,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwqkas4GGH8S8jutcmPgC1PY7TYuiO",
        memo: "!MAgEnta",
        height: 93111,
        timestamp: 9374188602,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwasdfDhGH8S8jutcmPgC1PY1sCv5B",
        memo: "No_magenta No magenta",
        height: 93133,
        timestamp: 9374188632,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz8TrZ9hCrHYZVViUufwghjkDhGH8S8jutcmPgC1WEQ4FBgh",
        memo: "no magenta = n0Magenta",
        height: 93145,
        timestamp: 9374188651,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbn0bOla",
        memo: "Magenta=magenta",
        height: 92891,
        timestamp: 9374188213,
        block_status: "Pending",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pbnf67GH",
        memo: "Magenta/magenta",
        height: 92891,
        timestamp: 9374188225,
        block_status: "Canonical",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pb8nbqnb",
        memo: "n0Magnta",
        height: 92903,
        timestamp: 9374188264,
        block_status: "Canonical",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgC1Pb4vpovr",
        memo: "n0Magenta = no magenta",
        height: 93145,
        timestamp: 9374188652,
        block_status: "Canonical",
        signal_status: "Invalid",
      },
      {
        account: "B62qp3Dsz9OyZ9hCrHqDwViAafrelreQwGH9Z9jutsmXgzVCX8nbP1C",
        memo: "!no--magenta",
        height: 93182,
        timestamp: 9374188900,
        block_status: "Canonical",
        signal_status: "Invalid",
      },
    ],
  },
];
