pub const NUM_SLOTS_IN_EPOCH: usize = 7140;
pub const COINBASE_REWARD_NON_SUPERCHARGED: i64 = 720;
pub const FOUNDATION_DELEGATION_PERCENTAGE_TO_PAY_BACK: i64 = 95;
pub const DIGITS_AFTER_DECIMAL_POINT: u32 = 9;
