/*
 Generated by typeshare 1.0.0
*/

//! Typeshare currently does not support serde derive annotations.
//! This leaves us unable to accurately generate our types.
//! Described in issue: https://github.com/1Password/typeshare/issues/65

export {};
