#! /bin/sh

set -e

is_darwin () {
  [ "$(uname -s)" = 'Darwin' ]
}

just
just destroy-db
just destroy-server
just image-build-web
just image-build-server
just clean-server
just clean-web
just build-images
just install
just install-server
just install-web
just lint-server
just lint-web
just lint
just build-server
just build-web-clean
just build-web
just build
just launch-db || is_darwin
just launch-server
just clean
just test-server
just test-web
just test
just destroy-all
