#! /bin/sh

set -e

just
just clean-server
just clean-web
just install-web
just build-web-clean
just image-build-web
just image-build-server
just image-build
just build-web
just build-server
just build
just test-web
just test-server
just test
just lint-web
just lint-server
just lint
just clean
